server.port=8080
server.servlet.context-path=/

# mysql
spring.datasource.url=*
spring.datasource.username=*
spring.datasource.password=*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# dify
dify.base-url=*
dify.api-key=*

# mybatis
mybatis.mapper-locations=classpath:mybatis/mapper/*.xml
mybatis.type-aliases-package=com.catowl.sts.model

# Redis
spring.redis.host=*
spring.redis.port=6379
spring.redis.database=*
spring.data.redis.host=*
spring.redis.timeout=10000
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-wait=-1
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0

# JWT
jwt.secret=*
jwt.expiration=86400000

# uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
file.upload-dir=${user.dir}/uploads
file.qrcode-dir=${user.dir}/qrcode

logging.level.com.catowl=debug
logging.file.name=/home/catowl/logs/catowl.log

# Swagger
springfox.documentation.swagger.v2.path=/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# MyBatis
mybatis.config-location=classpath:mybatis/Mybatis-config.xml

# frontend
frontend.base-url=*
